version: '3.9'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"

  logger-service:
    build:
      context: ./logger-service
      dockerfile: ./logger-service.dockerfile
    restart: always

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./authentication-service.dockerfile
    ports:
      - "8081:80"
    environment:
      # - DSN="postgresql://postgres:password@postgres:5432/users?sslmode=disable&connect_timeout=5&timezone=UTC"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users connect_timeout=5 timezone=UTC"
    depends_on:
      - postgres
    restart: always

  mailer-service:
    build:
      context: ./mailer-service
      dockerfile: ./mailer-service.dockerfile
    depends_on:
      - mailhog
    restart: always
    environment:
      MAIL_DOMAIN: "localhost"
      MAIL_HOST: "mailhog"
      MAIL_PORT: "1025"
      MAIL_ENCRYPTION: "none"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_EMAIL: "no-reply@localhost"
      FROM_NAME: "No Reply"

  postgres:
    image: postgres:latest
    ports:
        - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    restart: always
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logger
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "8025:8025"
      - "1025:1025"
