version: '3.9'

services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: ./authentication-service.dockerfile
    ports:
      - "8081:80"
    environment:
      # - DSN="postgresql://postgres:password@postgres:5432/users?sslmode=disable&connect_timeout=5&timezone=UTC"
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users connect_timeout=5 timezone=UTC"
    depends_on:
      - postgres
    restart: always


  postgres:
    image: postgres:latest
    ports:
        - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    restart: always

volumes:
  postgres:

